version: '3.4'
services:
  database:
    image: postgres:12
    container_name: database-krikey
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-krikey
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
    - redis-data:/data

  api:
    build: .
    image: api-krikey
    container_name: api-krikey
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - database
      - redis

volumes:
  postgres-data:
  redis-data:
